name: Deploy Develop
on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
  deploy-develop:
    uses: ./.github/workflows/deployment.yaml
    secrets: inherit
    needs: [tests]
    with:
      environment: develop
  deploy-test:
    uses: ./.github/workflows/deployment.yaml
    secrets: inherit
    needs: [tests]
    with:
      environment: test
