name: Deploy Preview
on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-develop:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: develop
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: | # ADD ALL ENV VARIABLES HERE
          yarn
          MONGO_URL="${{ secrets.MONGO_URL }}" \
          ENV="${{ secrets.ENV }}" \
          FIREBASE_PROJECT_ID="${{ secrets.FIREBASE_PROJECT_ID }}" \
          FIREBASE_PRIVATE_KEY="${{ secrets.FIREBASE_PRIVATE_KEY }}" \
          FIREBASE_CLIENT_EMAIL="${{ secrets.FIREBASE_CLIENT_EMAIL }}" \
          SENDGRID_API_KEY="${{ secrets.SENDGRID_API_KEY }}" \
          SENDGRID_EMAIL_SENDER="${{ secrets.SENDGRID_EMAIL_SENDER }}" \
          SENTRY_DSN="${{ secrets.SENTRY_DSN }}" \
          APP_BASE_URL="${{ secrets.APP_BASE_URL }}" \
          yarn build
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_SCOPE: ${{ secrets.VERCEL_TEAM_NAME }}
          DEPLOY_PR_FROM_FORK: true
